Repository RAF-SI-2024/Banka-2-Backend, pull requests merged in 2025-05, with the labels that each got.

#190 Create Link Project
  Bank.Application/Domain/Data.cs
  Bank.Application/Requests/OrderRequest.cs
  Bank.Application/Requests/TransactionRequest.cs
  Bank.Application/Responses/OrderResponse.cs
  Bank.Application/Validators/OrderValidator.cs
  Bank.ExchangeService/Application/ExchangeApplication.cs
  Bank.ExchangeService/BackgroundServices/OrderBackgroundService.cs
  Bank.ExchangeService/Bank.ExchangeService.csproj
  Bank.ExchangeService/Database/EntityConfigurations/OrderEntityConfiguration.cs
  Bank.ExchangeService/Database/Examples/OrderExample.cs
  Bank.ExchangeService/Database/Processors/IRealtimeProcessor.cs
  Bank.ExchangeService/HostedServices/ApplicationHostedService.cs
  Bank.ExchangeService/Mappers/OrderMapper.cs
  Bank.ExchangeService/Models/Order.cs
  Bank.ExchangeService/Repositories/OrderRepository.cs
  Bank.ExchangeService/Repositories/RedisRepository.cs
  Bank.ExchangeService/Services/OrderService.cs
  Bank.Link/Bank.Link.csproj
  Bank.Link/Configurations/JwtConfiguration.cs
  Bank.Link/Core/B3/B3ExchangeData.cs
  Bank.Link/Core/B3/B3UserData.cs
  Bank.Link/Core/BankData.cs
  Bank.Link/Core/BankExchangeData.cs
  Bank.Link/Core/BankUserData.cs
  Bank.Link/Endpoints/B3Endpoints.cs
  Bank.Link/LinkExtensions.cs
  Bank.Link/Mapper/B3/Content/AccountMapper.cs
  Bank.Link/Mapper/B3/Content/ClientMapper.cs
  Bank.Link/Mapper/B3/Query/AccountMapper.cs
  Bank.Link/Mapper/B3/Query/PageableMapper.cs
  Bank.Link/Queries/B3Queries.cs
  Bank.Link/Requests/B3Requests.cs
  Bank.Link/Responses/B3Responses.cs
  Bank.OpenApi/Examples/ConstantsExample.cs
  Bank.OpenApi/Examples/OrderExample.cs
  Bank.OpenApi/Mappers/OrderOpenApiMapper.cs
  Bank.OpenApi/OpenApiExtensions.cs
  Bank.OpenApi/Schemas/Swagger/EnumsSwaggerSchema.cs
  Bank.UserService/Services/TransactionService.cs
  Bank.sln
Labels: approved, lgtm

#191 Link
  Bank.Link/Bank.Link.csproj
  Bank.Link/Core/B3/B3UserData.cs
  Bank.Link/Core/BankData.cs
  Bank.Link/Core/DefaultData.cs
  Bank.Link/LinkExtensions.cs
  Bank.Link/Mapper/B3/Content/AccountMapper.cs
  Bank.Link/Mapper/B3/Content/ClientMapper.cs
  Bank.Link/Service/DataService.cs
Labels: approved, lgtm, size/L

#195 Implement OTP
  Bank.Application/Requests/TransactionRequest.cs
  Bank.OpenApi/Examples/ConstantsExample.cs
  Bank.OpenApi/Examples/TransactionExample.cs
  Bank.Permissions/Bank.Permissions.csproj
  Bank.Permissions/Services/AuthorizationService.cs
  Bank.UserService.Test/Integration/Steps/UserSteps.cs
  Bank.UserService/Services/TransactionService.cs
Labels: approved, lgtm, size/S

#199 Fixed loan service to work as intended and use transaction service within for dispersing funds
  Bank.UserService/Controllers/LoanController.cs
  Bank.UserService/HostedServices/LoanHostedService.cs
  Bank.UserService/Services/LoanService.cs
Labels: approved, lgtm, size/L

#200 Implement Process Security Transactions
  Bank.Application/Requests/TransactionRequest.cs
  Bank.UserService/BackgroundServices/TransactionBackgroundService.cs
  Bank.UserService/Database/EntityConfigurations/TransactionEntityConfiguration.cs
  Bank.UserService/Database/Seeders/AccountSeeder.cs
  Bank.UserService/Mappers/TransactionMapper.cs
  Bank.UserService/Models/Transaction.cs
  Bank.UserService/Repositories/AccountRepository.cs
  Bank.UserService/Services/DataService.cs
  Bank.UserService/Services/TransactionService.cs
Labels: approved, lgtm, size/L
