Repository RAF-SI-2024/Banka-2-Backend, pull requests merged in 2025-03, with the labels that each got.

#97 Improve scripts
  Scripts/Environments/user.env.template
  Scripts/clear_user_database.bat
  Scripts/clear_user_database.sh
  Scripts/compose.yaml
  Scripts/start_user.bat
  Scripts/start_user.sh
  Scripts/stop_all.bat
  Scripts/stop_all.sh
Labels: approved, size/M, lgtm

#98 Add ExchangeRate service and repository
  Bank.Application/Queries/ExchangeRateFilterQuery.cs
  Bank.Application/Requests/ExchangeRateRequest.cs
  Bank.Application/Responses/ExchangeRateResponse.cs
  Bank.UserService/Application/UserApplication.cs
  Bank.UserService/Database/ApplicationContext.cs
  Bank.UserService/Database/EntityConfigurations/CurrencyEntityConfiguration.cs
  Bank.UserService/Database/EntityConfigurations/ExchangeRateEntityConfiguration.cs
  Bank.UserService/Mappers/ExchangeRateMapper.cs
  Bank.UserService/Models/ExchangeRate.cs
  Bank.UserService/Repositories/CurrencyRepository.cs
  Bank.UserService/Repositories/ExchangeRateRepository.cs
  Bank.UserService/Services/ExchangeRateService.cs
Labels: approved, lgtm, size/L

#101 Little fixes
  Bank.UserService/Database/Seeders/AccountTypeSeeder.cs
Labels: approved, lgtm, size/XS

#99 Add controller, validators and cron job to Exchange Rate
  Bank.Application/Endpoints/Endpoints.cs
  Bank.Application/Utilities/ValidatorUtilities.cs
  Bank.Application/Validators/ExchangeRateValidator.cs
  Bank.Application/Validators/ValidationErrorMessage.cs
  Bank.UserService/Application/UserApplication.cs
  Bank.UserService/Controllers/ExchangeRateController.cs
  Bank.UserService/Database/EntityConfigurations/CompanyEntityConfiguration.cs
  Bank.UserService/HostedServices/ApplicationHostedService.cs
  Bank.UserService/HostedServices/ExchangeHostedService.cs
Labels: approved, lgtm, size/L

#103 Implement TransactionCode Entity
  Bank.Application/Utilities/ValidatorUtilities.cs
  Bank.Application/Validators/AccountValidator.cs
  Bank.Application/Validators/ValidationErrorMessage.cs
  Bank.UserService/Application/UserApplication.cs
  Bank.UserService/Database/ApplicationContext.cs
  Bank.UserService/Database/EntityConfigurations/TransactionCodeEntityConfiguration.cs
  Bank.UserService/Database/Seeders/TransactionCodeSeeder.cs
  Bank.UserService/HostedServices/DatabaseHostedService.cs
  Bank.UserService/HostedServices/ExchangeHostedService.cs
  Bank.UserService/Models/TransactionCode.cs
  Bank.UserService/Repositories/TransactionCodeRepository.cs
Labels: approved, lgtm, size/XL

#104 Implement TransactionTemplate Entity
  Bank.UserService/Application/UserApplication.cs
  Bank.UserService/Database/ApplicationContext.cs
  Bank.UserService/Database/EntityConfigurations/TransactionTemplateEntityConfiguration.cs
  Bank.UserService/Models/TransactionTemplate.cs
  Bank.UserService/Models/User.cs
  Bank.UserService/Repositories/TransactionTemplateRepository.cs
Labels: approved, lgtm, size/L

#105 Loan CRUD
  Bank.Application/Queries/LoanFilterQuery.cs
  Bank.UserService/Application/UserApplication.cs
  Bank.UserService/Database/ApplicationContext.cs
  Bank.UserService/Database/EntityConfigurations/InstallmentEntityConfiguration.cs
  Bank.UserService/Database/EntityConfigurations/LoanEntityConfiguration.cs
  Bank.UserService/Database/EntityConfigurations/LoanTypeEntityConfiguration.cs
  Bank.UserService/Database/Seeders/LoanTypeSeeder.cs
  Bank.UserService/HostedServices/DatabaseHostedService.cs
  Bank.UserService/Models/Installment.cs
  Bank.UserService/Models/InstallmentStatus.cs
  Bank.UserService/Models/InterestType.cs
  Bank.UserService/Models/Loan.cs
  Bank.UserService/Models/LoanStatus.cs
  Bank.UserService/Models/LoanType.cs
  Bank.UserService/Repositories/InstallmentRepository.cs
  Bank.UserService/Repositories/LoanRepository.cs
  Bank.UserService/Repositories/LoanTypeRepository.cs
Labels: approved, lgtm, size/XL

#106 Implement Transaction Entity
  Bank.Application/Domain/Data.cs
  Bank.Application/Queries/TransactionQuery.cs
  Bank.UserService/Application/UserApplication.cs
  Bank.UserService/Database/ApplicationContext.cs
  Bank.UserService/Database/EntityConfigurations/TransactionEntityConfiguration.cs
  Bank.UserService/Database/EntityConfigurations/UserEntityConfiguration.cs
  Bank.UserService/Models/Transaction.cs
  Bank.UserService/Repositories/TransactionRepository.cs
Labels: approved, lgtm, size/L

#107 Improvements
  Bank.Application/Endpoints/Endpoints.cs
  Bank.UserService/Controllers/AccountController.cs
  Bank.UserService/Controllers/CardController.cs
  Bank.UserService/Controllers/ClientController.cs
  Bank.UserService/Database/Seeders/AccountTypeSeeder.cs
  Bank.UserService/Repositories/AccountRepository.cs
  Bank.UserService/Repositories/CardRepository.cs
  Bank.UserService/Services/AccountService.cs
  Bank.UserService/Services/ClientService.cs
Labels: approved, lgtm, size/L

#108 Implement Endpoints for TransactionCode
  Bank.Application/Endpoints/Endpoints.cs
  Bank.Application/Responses/TransactionCodeResponse.cs
  Bank.UserService/Application/UserApplication.cs
  Bank.UserService/Controllers/TransactionCodeController.cs
  Bank.UserService/Database/Seeders/AccountCurrencySeeder.cs
  Bank.UserService/Database/Seeders/AccountSeeder.cs
  Bank.UserService/Mappers/TransactionCodeMapper.cs
  Bank.UserService/Services/TransactionCodeService.cs
Labels: approved, lgtm, size/L

#109 Improvements
  Bank.Application/Validators/AccountValidator.cs
Labels: approved, lgtm

#110 Implement Endpoints for TransactionTemplate
  Bank.Application/Endpoints/Endpoints.cs
  Bank.Application/Requests/TransactionTemplateRequest.cs
  Bank.Application/Responses/TransactionTemplateResponse.cs
  Bank.Application/Validators/TransactionTemplateValidator.cs
  Bank.UserService/Application/UserApplication.cs
  Bank.UserService/Controllers/TransactionTemplateController.cs
  Bank.UserService/Mappers/TransactionTemplateMapper.cs
  Bank.UserService/Services/TransactionTemplateService.cs
Labels: approved, lgtm, size/L

#111 Implement Endpoints for Transactions
  Bank.Application/Endpoints/Endpoints.cs
  Bank.Application/Requests/TransactionRequest.cs
  Bank.Application/Responses/TransactionResponse.cs
  Bank.Application/Validators/TransactionValidator.cs
  Bank.UserService/Application/UserApplication.cs
  Bank.UserService/Controllers/TransactionController.cs
  Bank.UserService/Mappers/TransactionMapper.cs
  Bank.UserService/Services/TransactionService.cs
Labels: approved, lgtm, size/L

#118 Refactor ExchangeRate entity
  Bank.Application/Endpoints/Endpoints.cs
  Bank.Application/Queries/ExchangeFilterQuery.cs
  Bank.Application/Queries/ExchangeRateFilterQuery.cs
  Bank.Application/Requests/ExchangeRateRequest.cs
  Bank.Application/Responses/ExchangeResponse.cs
  Bank.Application/Validators/ExchangeValidator.cs
  Bank.UserService/Application/UserApplication.cs
  Bank.UserService/Configurations/ExchangeConfiguration.cs
  Bank.UserService/Controllers/CurrencyController.cs
  Bank.UserService/Controllers/ExchangeController.cs
  Bank.UserService/Controllers/ExchangeRateController.cs
  Bank.UserService/Database/ApplicationContext.cs
  Bank.UserService/Database/EntityConfigurations/ExchangeEntityConfiguration.cs
  Bank.UserService/Database/EntityConfigurations/ExchangeRateEntityConfiguration.cs
  Bank.UserService/Database/Seeders/ExchangeSeeder.cs
  Bank.UserService/HostedServices/DatabaseHostedService.cs
  Bank.UserService/HostedServices/ExchangeHostedService.cs
  Bank.UserService/Mappers/ExchangeMapper.cs
  Bank.UserService/Mappers/ExchangeRateMapper.cs
  Bank.UserService/Models/Exchange.cs
  Bank.UserService/Repositories/CurrencyRepository.cs
  Bank.UserService/Repositories/ExchangeRateRepository.cs
  Bank.UserService/Repositories/ExchangeRepository.cs
  Bank.UserService/Services/CurrencyService.cs
  Bank.UserService/Services/ExchangeRateService.cs
  Bank.UserService/Services/ExchangeService.cs
Labels: size/XXL, approved, lgtm

#119 Loan controller
  Bank.Application/Endpoints/Endpoints.cs
  Bank.UserService/Controllers/InstallmentController.cs
  Bank.UserService/Controllers/LoanController.cs
  Bank.UserService/Controllers/LoanTypeController.cs
  Bank.UserService/Database/Seeders/InstallmentSeeder.cs
  Bank.UserService/Database/Seeders/LoanSeeder.cs
  Bank.UserService/HostedServices/DatabaseHostedService.cs
  Bank.UserService/Models/InterestType.cs
  Bank.UserService/Repositories/InstallmentRepository.cs
  Bank.UserService/Repositories/LoanRepository.cs
  Bank.UserService/Repositories/LoanTypeRepository.cs
Labels: approved, lgtm, size/XL

#120 Schemas
  Bank.UserService/Application/UserApplication.cs
  Bank.UserService/Swagger/SchemeFilters/AccountTypeSchemeFilter.cs
  Bank.UserService/Swagger/SchemeFilters/ExchangeSchemeFilter.cs
  Bank.UserService/Swagger/SchemeFilters/TransactionCodeSchemeFilter.cs
  Bank.UserService/Swagger/SchemeFilters/TransactionSchemeFilter.cs
  Bank.UserService/Swagger/SchemeFilters/TransactionTemplateSchemeFilter.cs
Labels: approved, lgtm, size/XL

#121 Some things
  Bank.Application/Endpoints/Endpoints.cs
Labels: approved, lgtm, size/XS

#122 Loan fix
  Bank.Application/Requests/InstallmentRequest.cs
  Bank.Application/Requests/LoanRequest.cs
  Bank.Application/Requests/LoanTypeRequest.cs
  Bank.Application/Responses/InstallmentResponse.cs
  Bank.Application/Responses/LoanResponse.cs
  Bank.Application/Responses/LoanTypeResponse.cs
  Bank.UserService/Application/UserApplication.cs
  Bank.UserService/Controllers/InstallmentController.cs
  Bank.UserService/Controllers/LoanController.cs
  Bank.UserService/Controllers/LoanTypeController.cs
  Bank.UserService/Mappers/InstallmentMapper.cs
  Bank.UserService/Mappers/LoanMapper.cs
  Bank.UserService/Models/LoanStatus.cs
  Bank.UserService/Services/InstallmentService.cs
  Bank.UserService/Services/LoanService.cs
  Bank.UserService/Services/LoanTypeService.cs
Labels: approved, lgtm, size/XL

#123 Schemas
  Bank.UserService/Application/UserApplication.cs
  Bank.UserService/Controllers/LoanTypeController.cs
  Bank.UserService/Database/Seeders/ExchangeSeeder.cs
  Bank.UserService/HostedServices/ExchangeHostedService.cs
  Bank.UserService/Services/LoanTypeService.cs
  Bank.UserService/Swagger/SchemeFilters/InstallmentSchemeFilter.cs
  Bank.UserService/Swagger/SchemeFilters/LoanSchemeFilter.cs
  Bank.UserService/Swagger/SchemeFilters/LoanTypeSchemeFilter.cs
Labels: approved, lgtm, size/L

#124 Unnecessary pull request
  Bank.Test/Bank.Test.csproj
  Bank.Test/Features/EmployeeController.feature
  Bank.Test/Features/EmployeeController.feature.cs
  Bank.Test/Features/UserController.feature
  Bank.Test/Features/UserController.feature.cs
  Bank.Test/Hooks/TestHooks.cs
  Bank.Test/Steps/EmployeeControllerSteps.cs
  Bank.Test/Steps/UserControllerSteps.cs
  Bank.UserService.Test.Unit/Bank.UserService.Test.Unit.csproj
  Bank.UserService.Test.Unit/UserServiceTests.cs
  Bank.UserService.Test/.env.template
  Bank.UserService.Test/.gitignore
  Bank.UserService.Test/Bank.UserService.Test.csproj
  Bank.UserService.Test/Drivers/Driver.cs
  Bank.UserService.Test/Examples/Entities/EmployeeEntity.cs
  Bank.UserService.Test/Examples/Entities/UserEntity.cs
  Bank.UserService.Test/Features/EmployeeController.feature
  Bank.UserService.Test/Features/UserController.feature
  Bank.UserService.Test/Hooks/Hook.cs
  Bank.UserService.Test/Steps/EmployeeSteps.cs
  Bank.UserService.Test/Steps/UserSteps.cs
  Bank.UserService/.env.template
  Bank.UserService/Application/UserApplication.cs
  Bank.UserService/Controllers/ExchangeController.cs
  Bank.UserService/HostedServices/DatabaseHostedService.cs
  Bank.sln
  msbuild.binlog
Labels: approved, lgtm

#125 Loan response updates
  Bank.Application/Domain/Data.cs
  Bank.Application/Endpoints/Endpoints.cs
  Bank.Application/Requests/InstallmentRequest.cs
  Bank.Application/Requests/LoanRequest.cs
  Bank.Application/Requests/LoanTypeRequest.cs
  Bank.Application/Responses/InstallmentResponse.cs
  Bank.Application/Responses/LoanResponse.cs
  Bank.UserService/Controllers/ClientController.cs
  Bank.UserService/Controllers/InstallmentController.cs
  Bank.UserService/Controllers/LoanController.cs
  Bank.UserService/Controllers/LoanTypeController.cs
  Bank.UserService/Database/Seeders/InstallmentSeeder.cs
  Bank.UserService/Database/Seeders/LoanSeeder.cs
  Bank.UserService/Mappers/CardMapper.cs
  Bank.UserService/Mappers/InstallmentMapper.cs
  Bank.UserService/Mappers/LoanMapper.cs
  Bank.UserService/Models/Installment.cs
  Bank.UserService/Models/InstallmentStatus.cs
  Bank.UserService/Models/InterestType.cs
  Bank.UserService/Models/Loan.cs
  Bank.UserService/Models/LoanStatus.cs
  Bank.UserService/Repositories/CardRepository.cs
  Bank.UserService/Repositories/InstallmentRepository.cs
  Bank.UserService/Repositories/LoanRepository.cs
  Bank.UserService/Repositories/LoanTypeRepository.cs
  Bank.UserService/Services/ClientService.cs
  Bank.UserService/Services/InstallmentService.cs
  Bank.UserService/Services/LoanService.cs
  Bank.UserService/Services/LoanTypeService.cs
  Bank.UserService/Swagger/SchemeFilters/InstallmentSchemeFilter.cs
  Bank.UserService/Swagger/SchemeFilters/LoanSchemeFilter.cs
  Bank.UserService/Swagger/SchemeFilters/LoanTypeSchemeFilter.cs
Labels: approved, lgtm, size/L

#126 Add some schemas
  Bank.UserService/Application/UserApplication.cs
  Bank.UserService/Swagger/SchemeFilters/InstallmentSchemeFilter.cs
  Bank.UserService/Swagger/SchemeFilters/LoanSchemeFilter.cs
  Bank.UserService/Swagger/SchemeFilters/LoanTypeSchemeFilter.cs
Labels: approved, size/M, lgtm

#127 Refined card generation
  Bank.UserService/Database/EntityConfigurations/CardEntityConfiguration.cs
  Bank.UserService/Mappers/CardMapper.cs
  Bank.UserService/Services/CardService.cs
  Bank.UserService/Utils/CardNumberGeneratorUtil.cs
Labels: approved, lgtm, size/L

#128 Some things
  Bank.Application/Endpoints/Endpoints.cs
  Bank.Application/Validators/AccountValidator.cs
  Bank.Application/Validators/CardValidator.cs
  Bank.Application/Validators/TransactionTemplateValidator.cs
  Bank.UserService/Application/UserApplication.cs
  Bank.UserService/Controllers/TransactionController.cs
  Bank.UserService/Repositories/TransactionRepository.cs
  Bank.UserService/Services/TransactionService.cs
Labels: approved, lgtm

#129 Add integration tests for Exchange service
  Bank.Application/Queries/ExchangeFilterQuery.cs
  Bank.Application/Requests/ExchangeRateRequest.cs
  Bank.Application/Validators/ExchangeValidator.cs
  Bank.UserService.Test/Examples/Entities/CurrencyEntity.cs
  Bank.UserService.Test/Examples/Entities/ExchangeEntity.cs
  Bank.UserService.Test/Features/Exchange.feature
  Bank.UserService.Test/Hooks/Hook.cs
  Bank.UserService.Test/Steps/ExchangeSteps.cs
  Bank.UserService/Controllers/ExchangeController.cs
  Bank.UserService/Database/Seeders/ExchangeSeeder.cs
  Bank.UserService/Models/Exchange.cs
  Bank.UserService/Repositories/ExchangeRepository.cs
  Bank.UserService/Services/ExchangeService.cs
  Bank.UserService/Swagger/SchemeFilters/ExchangeSchemeFilter.cs
Labels: approved, lgtm, size/XL

#131 Implement integration tests
  Bank.UserService.Test/Examples/Entities/AccountEntity.cs
  Bank.UserService.Test/Examples/Entities/CardEntity.cs
  Bank.UserService.Test/Examples/Entities/ClientEntity.cs
  Bank.UserService.Test/Examples/Entities/InstallmentEntity.cs
  Bank.UserService.Test/Examples/Entities/LoanEntity.cs
  Bank.UserService.Test/Examples/Entities/LoanTypeEntity.cs
  Bank.UserService.Test/Features/AccountController.feature
  Bank.UserService.Test/Features/AccountTypeController.feature
  Bank.UserService.Test/Features/CardController.feature
  Bank.UserService.Test/Features/CardTypeController.feature
  Bank.UserService.Test/Features/ClientController.feature
  Bank.UserService.Test/Features/InstallmentController.feature
  Bank.UserService.Test/Features/LoanController.feature
  Bank.UserService.Test/Features/LoanTypeController.feature
  Bank.UserService.Test/Steps/AccountSteps.cs
  Bank.UserService.Test/Steps/AccountTypeSteps.cs
  Bank.UserService.Test/Steps/CardSteps.cs
  Bank.UserService.Test/Steps/CardTypeSteps.cs
  Bank.UserService.Test/Steps/ClientSteps.cs
  Bank.UserService.Test/Steps/InstallmentSteps.cs
  Bank.UserService.Test/Steps/LoanSteps.cs
  Bank.UserService.Test/Steps/LoanTypeSteps.cs
  Bank.UserService/Application/UserApplication.cs
  Bank.UserService/Controllers/TransactionController.cs
  Bank.UserService/Services/TransactionService.cs
Labels: size/XXL, approved, lgtm

#132 Add tests for Company and Emoployee
  .gitignore
  Bank.Application/Extensions/StringExtensions.cs
  Bank.UserService.Test/Examples/Entities/CompanyEntity.cs
  Bank.UserService.Test/Examples/Entities/EmployeeEntity.cs
  Bank.UserService.Test/Features/CompanyController.feature
  Bank.UserService.Test/Features/EmployeeController.feature
  Bank.UserService.Test/Hooks/Hook.cs
  Bank.UserService.Test/Steps/CompanyStep.cs
  Bank.UserService.Test/Steps/EmployeeSteps.cs
Labels: approved, lgtm, size/XL

#133 Loan logic added
  Bank.Application/Endpoints/Endpoints.cs
  Bank.Application/Responses/LoanResponse.cs
  Bank.UserService/Application/UserApplication.cs
  Bank.UserService/Controllers/CardController.cs
  Bank.UserService/Controllers/LoanController.cs
  Bank.UserService/HostedServices/ApplicationHostedService.cs
  Bank.UserService/HostedServices/LoanHostedService.cs
  Bank.UserService/Mappers/InstallmentMapper.cs
  Bank.UserService/Repositories/InstallmentRepository.cs
  Bank.UserService/Repositories/LoanRepository.cs
  Bank.UserService/Services/LoanService.cs
Labels: approved, lgtm, size/XL

#135 Implement default sorting for transactions
  Bank.UserService/Mappers/AccountMapper.cs
  Bank.UserService/Repositories/TransactionRepository.cs
Labels: approved, lgtm, size/XS

#134 Fixed how we are checking currency Name to Code, and auth guards on the endpoints
  Bank.UserService/Controllers/LoanController.cs
  Bank.UserService/HostedServices/LoanHostedService.cs
  Bank.UserService/Repositories/LoanRepository.cs
Labels: approved, lgtm, size/XS

#137 Fixed some things for Loan and Installments
  Bank.Application/Responses/InstallmentResponse.cs
  Bank.UserService/Controllers/LoanController.cs
  Bank.UserService/HostedServices/LoanHostedService.cs
  Bank.UserService/Services/InstallmentService.cs
  Bank.UserService/Services/LoanService.cs
Labels: approved, size/M, lgtm

#138 Fixed formula for Variable Loans and added Email sending.
  Bank.UserService/HostedServices/LoanHostedService.cs
  Bank.UserService/Repositories/EmailRepository.cs
  Bank.UserService/Services/EmailService.cs
Labels: approved, size/M, lgtm

#141 Process Transactions
  Bank.Application/Domain/Data.cs
  Bank.Application/Endpoints/Endpoints.cs
  Bank.Application/Extensions/TimerExtensions.cs
  Bank.Application/Queries/BankQuery.cs
  Bank.Application/Responses/AccountResponse.cs
  Bank.Application/Responses/BankResponse.cs
  Bank.UserService.Test/Examples/Entities/UserEntity.cs
  Bank.UserService/Application/UserApplication.cs
  Bank.UserService/BackgroundServices/TransactionBackgroundService.cs
  Bank.UserService/Database/ApplicationContext.cs
  Bank.UserService/Database/EntityConfigurations/BankEntityConfiguration.cs
  Bank.UserService/Database/EntityConfigurations/TransactionEntityConfiguration.cs
  Bank.UserService/Database/Seeders/AccountCurrencySeeder.cs
  Bank.UserService/Database/Seeders/AccountSeeder.cs
  Bank.UserService/Database/Seeders/BankSeeder.cs
  Bank.UserService/Database/Seeders/ClientSeeder.cs
  Bank.UserService/Functions/IAccountBalance.cs
  Bank.UserService/HostedServices/ApplicationHostedService.cs
  Bank.UserService/HostedServices/DatabaseHostedService.cs
  Bank.UserService/Mappers/AccountMapper.cs
  Bank.UserService/Mappers/BankMapper.cs
  Bank.UserService/Mappers/TransactionMapper.cs
  Bank.UserService/Mappers/UserMapper.cs
  Bank.UserService/Models/Account.cs
  Bank.UserService/Models/AccountCurrency.cs
  Bank.UserService/Models/Bank.cs
  Bank.UserService/Models/Transaction.cs
  Bank.UserService/Models/User.cs
  Bank.UserService/Repositories/AccountRepository.cs
  Bank.UserService/Repositories/BankRepository.cs
  Bank.UserService/Repositories/ExchangeRepository.cs
  Bank.UserService/Repositories/UserRepository.cs
  Bank.UserService/Services/BankService.cs
  Bank.UserService/Services/TransactionService.cs
Labels: approved, lgtm

#144 My PR
  Bank.UserService.Test/Examples/Entities/TransactionEntity.cs
  Bank.UserService.Test/Hooks/Hook.cs
  Bank.UserService/BackgroundServices/TransactionBackgroundService.cs
  Bank.UserService/HostedServices/ApplicationHostedService.cs
  Scripts/User/Dockerfile
  Scripts/compose.yaml
  Scripts/start_user_database.bat
  Scripts/start_user_database.sh
  Scripts/start_user_service.bat
  Scripts/start_user_service.sh
Labels: approved, size/M, lgtm

#143 Refactor User, Client, Employee, Company, Country
  Bank.UserService/Mappers/CompanyMapper.cs
  Bank.UserService/Mappers/UserMapper.cs
  Bank.UserService/Repositories/CompanyRepository.cs
  Bank.UserService/Repositories/CountryRepository.cs
  Bank.UserService/Repositories/UserRepository.cs
  Bank.UserService/Services/ClientService.cs
  Bank.UserService/Services/CompanyService.cs
  Bank.UserService/Services/EmployeeService.cs
Labels: approved, lgtm, size/L

#142 Add entity samples
  Bank.UserService.Test/Examples/Entities/AccountEntity.cs
  Bank.UserService.Test/Examples/Entities/CardEntity.cs
  Bank.UserService.Test/Examples/Entities/ClientEntity.cs
  Bank.UserService.Test/Examples/Entities/CompanyEntity.cs
  Bank.UserService.Test/Examples/Entities/EmployeeEntity.cs
  Bank.UserService.Test/Examples/Entities/ExchangeEntity.cs
  Bank.UserService.Test/Examples/Entities/InstallmentEntity.cs
  Bank.UserService.Test/Examples/Entities/LoanEntity.cs
  Bank.UserService.Test/Examples/Entities/LoanTypeEntity.cs
  Bank.UserService.Test/Examples/Entities/TransactionEntity.cs
  Bank.UserService.Test/Examples/Entities/TransactionTemplateEntity.cs
  Bank.UserService.Test/Examples/Entities/UserEntity.cs
  Bank.UserService.Test/Features/AccountController.feature
  Bank.UserService.Test/Features/AccountTypeController.feature
  Bank.UserService.Test/Features/CardController.feature
  Bank.UserService.Test/Features/CardTypeController.feature
  Bank.UserService.Test/Features/ClientController.feature
  Bank.UserService.Test/Features/InstallmentController.feature
  Bank.UserService.Test/Features/LoanController.feature
  Bank.UserService.Test/Features/LoanTypeController.feature
  Bank.UserService.Test/Steps/AccountSteps.cs
  Bank.UserService.Test/Steps/AccountTypeSteps.cs
  Bank.UserService.Test/Steps/CardSteps.cs
  Bank.UserService.Test/Steps/CardTypeSteps.cs
  Bank.UserService.Test/Steps/ClientSteps.cs
  Bank.UserService.Test/Steps/InstallmentSteps.cs
  Bank.UserService.Test/Steps/LoanSteps.cs
  Bank.UserService.Test/Steps/LoanTypeSteps.cs
  Bank.UserService/Database/Sample/AccountCurrencySample.cs
  Bank.UserService/Database/Sample/AccountSample.cs
  Bank.UserService/Database/Sample/AccountTypeSample.cs
  Bank.UserService/Database/Sample/CardSample.cs
  Bank.UserService/Database/Sample/ClientSample.cs
  Bank.UserService/Database/Sample/CompanySample.cs
  Bank.UserService/Database/Sample/EmployeeSample.cs
  Bank.UserService/Database/Sample/ExchangeSample.cs
  Bank.UserService/Database/Sample/InstallmentSample.cs
  Bank.UserService/Database/Sample/LoanSample.cs
  Bank.UserService/Database/Sample/LoanTypeSample.cs
  Bank.UserService/Database/Sample/TransactionSample.cs
  Bank.UserService/Database/Sample/TransactionTemplateSample.cs
  Bank.UserService/Database/Sample/UserSample.cs
  Bank.UserService/Database/Seeders/LoanTypeSeeder.cs
  Bank.UserService/HostedServices/DatabaseHostedService.cs
  Bank.UserService/Swagger/SchemeFilters/AccountCurrencySchemeFilter.cs
  Bank.UserService/Swagger/SchemeFilters/AccountSchemeFilter.cs
  Bank.UserService/Swagger/SchemeFilters/AccountTypeSchemeFilter.cs
  Bank.UserService/Swagger/SchemeFilters/CardSchemeFilter.cs
  Bank.UserService/Swagger/SchemeFilters/CardTypeSchemeFilter.cs
  Bank.UserService/Swagger/SchemeFilters/ClientSchemeFilter.cs
  Bank.UserService/Swagger/SchemeFilters/CompanySchemeFilter.cs
  Bank.UserService/Swagger/SchemeFilters/EmployeeSchemeFilter.cs
  Bank.UserService/Swagger/SchemeFilters/ExchangeSchemeFilter.cs
  Bank.UserService/Swagger/SchemeFilters/InstallmentSchemeFilter.cs
  Bank.UserService/Swagger/SchemeFilters/LoanSchemeFilter.cs
  Bank.UserService/Swagger/SchemeFilters/LoanTypeSchemeFilter.cs
  Bank.UserService/Swagger/SchemeFilters/TransactionCodeSchemeFilter.cs
  Bank.UserService/Swagger/SchemeFilters/TransactionSchemeFilter.cs
  Bank.UserService/Swagger/SchemeFilters/TransactionTemplateSchemeFilter.cs
  Bank.UserService/Swagger/SchemeFilters/UserSchemeFilter.cs
Labels: size/XXL, approved, lgtm

#151 StockExchange, Listing and ListingHistorical
  Bank.Application/Endpoints/Endpoints.cs
  Bank.Application/Queries/ListingFilterQuery.cs
  Bank.Application/Queries/ListingHistoricalQuery.cs
  Bank.Application/Queries/StockExchangeQuery.cs
  Bank.Application/Responses/ListingHistoricalResponse.cs
  Bank.Application/Responses/ListingResponse.cs
  Bank.Application/Responses/StockExchangeResponse.cs
  Bank.ExchangeService/Application/ExchangeApplication.cs
  Bank.ExchangeService/Controllers/ListingController.cs
  Bank.ExchangeService/Controllers/ListingHistoricalController.cs
  Bank.ExchangeService/Controllers/StockExchangeController.cs
  Bank.ExchangeService/Database/DatabaseContext.cs
  Bank.ExchangeService/Database/EntityConfigurations/ListingEntityConfiguration.cs
  Bank.ExchangeService/Database/EntityConfigurations/ListingHistoricalEntityConfiguration.cs
  Bank.ExchangeService/Database/EntityConfigurations/StockExchangeEntityConfiguration.cs
  Bank.ExchangeService/Database/Seeders/ListingHistoricalSeeder.cs
  Bank.ExchangeService/Database/Seeders/ListingSeeder.cs
  Bank.ExchangeService/Database/Seeders/StockExchangeSeeder.cs
  Bank.ExchangeService/Database/Seeders/resource/exchanges.csv
  Bank.ExchangeService/HostedServices/ApplicationHostedService.cs
  Bank.ExchangeService/HostedServices/DatabaseHostedService.cs
  Bank.ExchangeService/HttpClients/CurrencyClient.cs
  Bank.ExchangeService/Mappers/ListingHistoricalMapper.cs
  Bank.ExchangeService/Mappers/ListingMapper.cs
  Bank.ExchangeService/Mappers/StockExchangeMapper.cs
  Bank.ExchangeService/Models/Listing.cs
  Bank.ExchangeService/Models/ListingHistorical.cs
  Bank.ExchangeService/Models/StockExchange.cs
  Bank.ExchangeService/Repositorties/ListingHistoricalRepository.cs
  Bank.ExchangeService/Repositorties/ListingRepository.cs
  Bank.ExchangeService/Repositorties/StockExchangeRepository.cs
  Bank.ExchangeService/Services/ListingHistoricalService.cs
  Bank.ExchangeService/Services/ListingService.cs
  Bank.ExchangeService/Services/StockExchangeService.cs
Labels: size/XXL, approved, lgtm
