Repository RAF-SI-2024/Banka-2-Backend, pull requests merged in 2025-04, with the labels that each got.

#152 Authorization upgrade
  Bank.Application/Domain/Data.cs
  Bank.Application/Domain/Permission.cs
  Bank.Application/Requests/ClientRequest.cs
  Bank.Application/Requests/EmployeeRequest.cs
  Bank.Application/Requests/UpdatePermissionsRequest.cs
  Bank.UserService/Application/UserApplication.cs
  Bank.UserService/Controllers/ClientController.cs
  Bank.UserService/Controllers/UserController.cs
  Bank.UserService/Database/EntityConfigurations/UserEntityConfiguration.cs
  Bank.UserService/Database/Sample/ClientSample.cs
  Bank.UserService/Database/Sample/EmployeeSample.cs
  Bank.UserService/Database/Seeders/ClientSeeder.cs
  Bank.UserService/Database/Seeders/EmployeeSeeder.cs
  Bank.UserService/Mappers/UserMapper.cs
  Bank.UserService/Models/User.cs
  Bank.UserService/Security/AuthorizeAttribute.cs
  Bank.UserService/Security/PermissionHandelrs.cs
  Bank.UserService/Security/PermissionPolicyProvider.cs
  Bank.UserService/Security/RequirePermissionAttribute.cs
  Bank.UserService/Security/TokenProvider.cs
  Bank.UserService/Services/AuthorizationService.cs
  Bank.UserService/Services/UserService.cs
Labels: approved, lgtm, size/L

#153 Revert "Authorization upgrade"
  Bank.Application/Domain/Data.cs
  Bank.Application/Domain/Permission.cs
  Bank.Application/Requests/ClientRequest.cs
  Bank.Application/Requests/EmployeeRequest.cs
  Bank.Application/Requests/UpdatePermissionsRequest.cs
  Bank.UserService/Application/UserApplication.cs
  Bank.UserService/Controllers/ClientController.cs
  Bank.UserService/Controllers/UserController.cs
  Bank.UserService/Database/EntityConfigurations/UserEntityConfiguration.cs
  Bank.UserService/Database/Sample/ClientSample.cs
  Bank.UserService/Database/Sample/EmployeeSample.cs
  Bank.UserService/Database/Seeders/ClientSeeder.cs
  Bank.UserService/Database/Seeders/EmployeeSeeder.cs
  Bank.UserService/Mappers/UserMapper.cs
  Bank.UserService/Models/User.cs
  Bank.UserService/Security/AuthorizeAttribute.cs
  Bank.UserService/Security/PermissionHandelrs.cs
  Bank.UserService/Security/PermissionPolicyProvider.cs
  Bank.UserService/Security/RequirePermissionAttribute.cs
  Bank.UserService/Security/TokenProvider.cs
  Bank.UserService/Services/AuthorizationService.cs
  Bank.UserService/Services/UserService.cs
Labels: approved, lgtm, size/L

#150 Refactor mappes and request/responses
  Bank.Application/Domain/Data.cs
  Bank.Application/Domain/Permission.cs
  Bank.Application/Endpoints/Endpoints.cs
  Bank.Application/Requests/CardRequest.cs
  Bank.Application/Requests/ClientRequest.cs
  Bank.Application/Requests/EmployeeRequest.cs
  Bank.Application/Requests/InstallmentCreateRequest.cs
  Bank.Application/Requests/LoanCreateRequest.cs
  Bank.Application/Requests/LoanTypeCreateRequest.cs
  Bank.Application/Requests/UpdatePermissionsRequest.cs
  Bank.UserService.Test/Integration/Examples/Entities/CardEntity.cs
  Bank.UserService.Test/Integration/Examples/Entities/InstallmentEntity.cs
  Bank.UserService.Test/Integration/Examples/Entities/LoanEntity.cs
  Bank.UserService.Test/Integration/Examples/Entities/LoanTypeEntity.cs
  Bank.UserService.Test/Integration/Steps/CardSteps.cs
  Bank.UserService.Test/Integration/Steps/InstallmentSteps.cs
  Bank.UserService.Test/Integration/Steps/LoanSteps.cs
  Bank.UserService.Test/Integration/Steps/LoanTypeSteps.cs
  Bank.UserService/Application/UserApplication.cs
  Bank.UserService/Controllers/CardController.cs
  Bank.UserService/Controllers/InstallmentController.cs
  Bank.UserService/Controllers/LoanController.cs
  Bank.UserService/Controllers/LoanTypeController.cs
  Bank.UserService/Controllers/UserController.cs
  Bank.UserService/Database/EntityConfigurations/BankEntityConfiguration.cs
  Bank.UserService/Database/EntityConfigurations/TransactionEntityConfiguration.cs
  Bank.UserService/Database/EntityConfigurations/UserEntityConfiguration.cs
  Bank.UserService/Database/Sample/CardSample.cs
  Bank.UserService/Database/Sample/ClientSample.cs
  Bank.UserService/Database/Sample/EmployeeSample.cs
  Bank.UserService/Database/Sample/InstallmentSample.cs
  Bank.UserService/Database/Sample/LoanSample.cs
  Bank.UserService/Database/Sample/LoanTypeSample.cs
  Bank.UserService/Database/Seeders/ClientSeeder.cs
  Bank.UserService/Database/Seeders/EmployeeSeeder.cs
  Bank.UserService/HostedServices/DatabaseHostedService.cs
  Bank.UserService/HostedServices/LoanHostedService.cs
  Bank.UserService/Mappers/CardMapper.cs
  Bank.UserService/Mappers/InstallmentMapper.cs
  Bank.UserService/Mappers/LoanMapper.cs
  Bank.UserService/Mappers/UserMapper.cs
  Bank.UserService/Models/Loan.cs
  Bank.UserService/Models/User.cs
  Bank.UserService/Repositories/LoanRepository.cs
  Bank.UserService/Repositories/LoanTypeRepository.cs
  Bank.UserService/Repositories/UserRepository.cs
  Bank.UserService/Security/AuthorizeAttribute.cs
  Bank.UserService/Security/PermissionHandler.cs
  Bank.UserService/Security/PermissionPolicyProvider.cs
  Bank.UserService/Security/RequirePermission.cs
  Bank.UserService/Services/AuthorizationService.cs
  Bank.UserService/Services/CardService.cs
  Bank.UserService/Services/InstallmentService.cs
  Bank.UserService/Services/LoanService.cs
  Bank.UserService/Services/LoanTypeService.cs
  Bank.UserService/Services/UserService.cs
  Bank.UserService/Swagger/SchemeFilters/CardSchemeFilter.cs
  Bank.UserService/Swagger/SchemeFilters/InstallmentSchemeFilter.cs
  Bank.UserService/Swagger/SchemeFilters/LoanSchemeFilter.cs
  Bank.UserService/Swagger/SchemeFilters/LoanTypeSchemeFilter.cs
Labels: approved, lgtm, size/XL

#158 Some Things
  Bank.UserService.Test/Integration/Examples/Entities/EmployeeEntity.cs
  Bank.UserService.Test/Integration/Examples/Entities/UserEntity.cs
  Bank.UserService/Mappers/AccountCurrencyMapper.cs
  Bank.UserService/Mappers/AccountMapper.cs
  Bank.UserService/Mappers/CardMapper.cs
  Bank.UserService/Mappers/CompanyMapper.cs
  Bank.UserService/Mappers/ExchangeMapper.cs
  Bank.UserService/Mappers/TransactionMapper.cs
  Bank.UserService/Models/Loan.cs
  Bank.UserService/Repositories/CardRepository.cs
  Bank.UserService/Services/AccountCurrencyService.cs
  Bank.UserService/Services/AccountService.cs
  Bank.UserService/Services/CompanyService.cs
Labels: approved, lgtm, size/L

#159 Boshko fixes
  Bank.UserService/Mappers/CardMapper.cs
  Bank.UserService/Services/CardService.cs
Labels: approved, lgtm

#161 Prepare Deployment
  Bank.UserService/Models/Account.cs
  Bank.UserService/Repositories/AccountRepository.cs
  Scripts/User/Dockerfile
Labels: approved, lgtm

#163 Boshko
  Bank.Application/Responses/TransactionResponse.cs
  Bank.UserService/Mappers/TransactionMapper.cs
  Bank.UserService/Swagger/SchemeFilters/TransactionSchemeFilter.cs
Labels: approved, lgtm, size/S

#164 Boshko :)
  Bank.Application/Endpoints/Endpoints.cs
Labels: approved, lgtm

#165 Boshko!
  Bank.UserService/Mappers/TransactionMapper.cs
Labels: approved, lgtm, size/XS

#167 Fix typo
  .prow/build.yaml
Labels: approved, lgtm, size/XS

#173 Library Integration
  Bank.Application/Endpoints/Endpoints.cs
  Bank.ExchangeService/.env.template
  Bank.ExchangeService/Application/ExchangeApplication.cs
  Bank.ExchangeService/Bank.ExchangeService.csproj
  Bank.ExchangeService/Configurations/JwtConfiguration.cs
  Bank.Http/Clients/User/LoanHttpClient.cs
  Bank.Http/Configurations/JwtConfiguration.cs
  Bank.Http/HttpExtensions.cs
  Bank.UserService/Controllers/LoanController.cs
Labels: approved, lgtm, size/L

#177 Assets and Orders
  Bank.Application/Domain/Data.cs
  Bank.Application/Domain/Pageable.cs
  Bank.Application/Queries/AccountQuery.cs
  Bank.Application/Queries/AssetQuery.cs
  Bank.Application/Requests/OrderRequest.cs
  Bank.Application/Responses/AssetResponse.cs
  Bank.Application/Responses/OrderResponse.cs
  Bank.Application/Validators/OrderValidator.cs
  Bank.ExchangeService/Database/DatabaseContext.cs
  Bank.ExchangeService/Database/EntityConfigurations/AssetEntityConfiguration.cs
  Bank.ExchangeService/Database/EntityConfigurations/OrderEntityConfiguration.cs
  Bank.ExchangeService/Mappers/AssetMapper.cs
  Bank.ExchangeService/Mappers/OrderMapper.cs
  Bank.ExchangeService/Models/Asset.cs
  Bank.ExchangeService/Models/Order.cs
  Bank.ExchangeService/Repositories/AssetRepository.cs
  Bank.ExchangeService/Services/AssetService.cs
  Bank.ExchangeService/Services/OrderService.cs
Labels: approved, lgtm, size/XL

#179 Fix Pageable
  Bank.Application/Domain/Pageable.cs
Labels: approved, lgtm, size/XS

#181 Update user env template
  Bank.UserService/.env.template
Labels: approved, lgtm, size/S

#182 Database Improvements
  Bank.Database/Core/DatabaseContextFactory.cs
  Bank.UserService/BackgroundServices/DatabaseBackgroundService.cs
  Bank.UserService/Services/DataService.cs
  Bank.UserService/Services/TransactionService.cs
Labels: approved, lgtm, size/L

#183 PR
  Bank.Database/Core/DatabaseContext.cs
  Bank.Database/Core/DatabaseContextFactory.cs
  Bank.Database/Core/DatabaseContextPool.cs
  Bank.Database/DatabaseExtensions.cs
  Bank.ExchangeService/Application/ExchangeApplication.cs
  Bank.ExchangeService/Bank.ExchangeService.csproj
  Bank.ExchangeService/Database/DatabaseContext.cs
  Bank.ExchangeService/Repositories/AssetRepository.cs
  Bank.ExchangeService/Repositories/OrderRepository.cs
  Bank.ExchangeService/Repositories/QuoteRepository.cs
  Bank.ExchangeService/Repositories/SecurityRepository.cs
  Bank.ExchangeService/Repositories/StockExchangeRepository.cs
  Bank.ExchangeService/Services/AuthorizationService.cs
  Bank.Permissions/AuthorizationExtensions.cs
  Bank.Permissions/Services/AuthorizationService.cs
  Bank.Permissions/Services/AuthorizationServiceFactory.cs
  Bank.UserService/Mappers/LoanMapper.cs
  Bank.UserService/Repositories/TransactionRepository.cs
  Bank.UserService/Repositories/TransactionTemplateRepository.cs
  Bank.UserService/Services/AccountCurrencyService.cs
  Bank.UserService/Services/AccountService.cs
  Bank.UserService/Services/EmailService.cs
  Bank.UserService/Services/TransactionService.cs
  Bank.UserService/Services/TransactionTemplateService.cs
  Bank.UserService/Services/UserService.cs
Labels: approved, lgtm, size/XL

#184 Fix
  Bank.Application/Endpoints/Endpoints.cs
Labels: approved, lgtm, size/XS

#186 Apply Changes
  Bank.ExchangeService.Test/Hooks/Hook.cs
  Bank.ExchangeService/Configurations/DatabaseConfiguration.cs
  Bank.UserService.Test/Integration/Steps/AccountSteps.cs
  Bank.UserService.Test/Integration/Steps/TransactionCodeSteps.cs
  Bank.UserService.Test/Integration/Steps/TransactionTemplateSteps.cs
  Bank.UserService/Configurations/DatabaseConfiguration.cs
Labels: approved, size/M, lgtm

#187 SFix
  Bank.UserService.Test/Integration/Steps/AccountCurrencySteps.cs
Labels: approved, lgtm, size/XS

#188 Implement Authorization Service for Testing
  Bank.UserService.Test/Bank.UserService.Test.csproj
  Bank.UserService.Test/Integration/Hooks/Hook.cs
  Bank.UserService.Test/Integration/Services/TestAuthorizationServiceFactory.cs
  Bank.UserService.Test/Integration/Steps/AccountCurrencySteps.cs
  Bank.UserService.Test/Integration/Steps/AccountSteps.cs
  Bank.UserService.Test/Integration/Steps/TransactionTemplateSteps.cs
  Bank.UserService.Test/Integration/Steps/UserSteps.cs
Labels: approved, lgtm, size/L

#189 Refactor Securities and StockExchange to use UserHttpClient
  Bank.Application/Endpoints/Endpoints.cs
  Bank.Application/Queries/AccountQuery.cs
  Bank.Application/Queries/AssetQuery.cs
  Bank.Application/Requests/OrderRequest.cs
  Bank.Database/Configurations/DatabaseConfiguration.cs
  Bank.Database/DatabaseExtensions.cs
  Bank.ExchangeService/.env.template
  Bank.ExchangeService/BackgroundServices/DatabaseBackgroundService.cs
  Bank.ExchangeService/Database/Seeders/ForexPairSeeder.cs
  Bank.ExchangeService/Extensions/HttpClientExtensions.cs
  Bank.ExchangeService/Repositories/AssetRepository.cs
  Bank.ExchangeService/Repositories/QuoteRepository.cs
  Bank.ExchangeService/Repositories/StockExchangeRepository.cs
  Bank.ExchangeService/Services/ForexPairService.cs
  Bank.ExchangeService/Services/FutureContractService.cs
  Bank.ExchangeService/Services/OptionService.cs
  Bank.ExchangeService/Services/StockExchangeService.cs
  Bank.ExchangeService/Services/StockService.cs
  Bank.Http/Clients/User/CurrencyHttpClient.cs
  Bank.Http/Clients/User/UserHttpClient.cs
  Bank.Http/Clients/User/UserServiceHttpClient.cs
  Bank.OpenApi/Examples/UserExample.cs
  Bank.OpenApi/Mappers/OrderOpenApiMapper.cs
  Bank.OpenApi/Mappers/UserOpenApiMapper.cs
  Bank.OpenApi/Schemas/Swagger/UserSwaggerSchema.cs
  Bank.UserService.Test/Integration/Examples/Entities/AccountCurrencyEntity.cs
  Bank.UserService.Test/Integration/Examples/Entities/BankEntity.cs
  Bank.UserService.Test/Integration/Examples/Entities/EmailEntity.cs
  Bank.UserService.Test/Integration/Examples/Entities/LoanEntity.cs
  Bank.UserService.Test/Integration/Examples/Entities/UserEntity.cs
  Bank.UserService.Test/Integration/Hooks/Hook.cs
  Bank.UserService.Test/Integration/Services/TestAuthorizationServiceFactory.cs
  Bank.UserService.Test/Integration/Steps/AccountCurrencySteps.cs
  Bank.UserService.Test/Integration/Steps/AccountSteps.cs
  Bank.UserService.Test/Integration/Steps/EmailSteps.cs
  Bank.UserService.Test/Integration/Steps/TransactionTemplateSteps.cs
  Bank.UserService.Test/Integration/Steps/UserSteps.cs
  Bank.UserService/Database/Examples/UserExample.cs
  Bank.UserService/HostedServices/ApplicationHostedService.cs
  Bank.UserService/Repositories/UserRepository.cs
  Bank.UserService/Services/DataService.cs
  Bank.UserService/Services/DefaultService.cs
  Bank.UserService/Services/TransactionService.cs
  Bank.UserService/Services/TransactionTemplateService.cs
  Bank.UserService/Services/UserService.cs
Labels: approved, lgtm, size/L
