Repository RAF-SI-2024/Banka-2-Backend, pull requests merged in 2025-06, with the labels that each got.

#204 Add SecuritySimpleResponse
  Bank.Application/Endpoints/Endpoints.cs
  Bank.Application/Responses/SecurityResponse.cs
  Bank.ExchangeService/Application/ExchangeApplication.cs
  Bank.ExchangeService/Configurations/HttpClientConfiguration.cs
  Bank.ExchangeService/Controllers/SecurityController.cs
  Bank.ExchangeService/Mappers/SecurityMapper.cs
  Bank.ExchangeService/Repositories/SecurityRepository.cs
  Bank.ExchangeService/Services/SecurityService.cs
Labels: approved, lgtm, size/L

#206 Loans and exchanges
  Bank.Application/Endpoints/Endpoints.cs
  Bank.Application/Responses/StockExchangeResponse.cs
  Bank.ExchangeService/Application/ExchangeApplication.cs
  Bank.ExchangeService/BackgroundServices/DatabaseBackgroundService.cs
  Bank.ExchangeService/Database/EntityConfigurations/StockExchangeEntityConfiguration.cs
  Bank.ExchangeService/Database/Examples/StockExchangeExample.cs
  Bank.ExchangeService/Database/Seeders/StockExchangeSeeder.cs
  Bank.ExchangeService/Mappers/StockExchangeMapper.cs
  Bank.ExchangeService/Models/StockExchange.cs
  Bank.OpenApi/Examples/StockExchangeExample.cs
  Bank.UserService/Controllers/LoanController.cs
  Bank.UserService/Database/Seeders/AccountSeeder.cs
  Bank.UserService/HostedServices/LoanHostedService.cs
  Bank.UserService/Repositories/LoanRepository.cs
Labels: approved, lgtm, size/L

#211 Smt
  Bank.ExchangeService/Application/ExchangeApplication.cs
  Bank.ExchangeService/BackgroundServices/DatabaseBackgroundService.cs
Labels: approved, lgtm, size/S

#212 Exchange | Fuck off
  Bank.ExchangeService.Test/Database/Seeders/resource/exchanges.csv
  Bank.ExchangeService.Test/Database/Seeders/resource/futures_data.csv
  Bank.ExchangeService.Test/Database/Seeders/resource/quotes_30min_2days.csv
  Bank.ExchangeService.Test/Hooks/Hook.cs
  Bank.ExchangeService/BackgroundServices/DatabaseBackgroundService.cs
  Bank.ExchangeService/Database/Seeders/StockExchangeSeeder.cs
Labels: approved, lgtm, size/L

#213 fix: Security and StockExchange seeders
  Bank.ExchangeService/BackgroundServices/DatabaseBackgroundService.cs
  Bank.ExchangeService/BackgroundServices/StockBackgroundService.cs
  Bank.ExchangeService/Database/Seeders/OptionSeeder.cs
  Bank.ExchangeService/Database/Seeders/QuoteSeeder.cs
  Bank.ExchangeService/Database/Seeders/StockExchangeSeeder.cs
  Bank.ExchangeService/Database/Seeders/StockSeeder.cs
  Bank.ExchangeService/Repositories/SecurityRepository.cs
Labels: approved, lgtm, size/L

#214 Fixed installment
  Bank.UserService/Mappers/InstallmentMapper.cs
  Bank.UserService/Repositories/InstallmentRepository.cs
Labels: approved, lgtm, size/S

#220 Development
  Bank.ExchangeService/Database/Processors/PersistentRealtimeProcessor.cs
  Bank.ExchangeService/Database/Seeders/FutureContractSeeder.cs
Labels: approved, lgtm, size/L

#222 Merge development into production
  Bank.Application/ApplicationInfo.cs
  Bank.Database/Configurations/DatabaseConfiguration.cs
  Bank.ExchangeService/.env.template
  Bank.ExchangeService/Bank.ExchangeService.csproj
  Bank.ExchangeService/HostedServices/ApplicationHostedService.cs
  Bank.ExchangeService/appsettings.Development.json
  Bank.UserService/Bank.UserService.csproj
  Bank.UserService/HostedServices/ApplicationHostedService.cs
  Bank.UserService/appsettings.json
  Bank.sln
Labels: approved, lgtm, size/L

#223 Pull Request
  Bank.ExchangeService/Application/ExchangeApplication.cs
  Bank.ExchangeService/BackgroundServices/DatabaseBackgroundService.cs
  Bank.ExchangeService/BackgroundServices/ForexPairBackgroundService.cs
  Bank.ExchangeService/BackgroundServices/OptionBackgroundService.cs
  Bank.ExchangeService/BackgroundServices/StockBackgroundService.cs
  Bank.ExchangeService/Database/Seeders/OptionSeeder.cs
  Bank.ExchangeService/HostedServices/ApplicationHostedService.cs
  Bank.ExchangeService/Repositories/SecurityRepository.cs
  Bank.ExchangeService/appsettings.json
  Bank.UserService/Application/UserApplication.cs
  Bank.UserService/Properties/launchSettings.json
  Bank.UserService/appsettings.json
Labels: approved, lgtm, size/L

#224 Merge development into production
  Bank.ExchangeService/Application/ExchangeApplication.cs
  Bank.ExchangeService/BackgroundServices/DatabaseBackgroundService.cs
  Bank.ExchangeService/BackgroundServices/ForexPairBackgroundService.cs
  Bank.ExchangeService/BackgroundServices/OptionBackgroundService.cs
  Bank.ExchangeService/BackgroundServices/StockBackgroundService.cs
  Bank.ExchangeService/Database/Seeders/OptionSeeder.cs
  Bank.ExchangeService/HostedServices/ApplicationHostedService.cs
  Bank.ExchangeService/Repositories/SecurityRepository.cs
  Bank.ExchangeService/appsettings.json
  Bank.UserService/Application/UserApplication.cs
  Bank.UserService/Properties/launchSettings.json
  Bank.UserService/appsettings.json
Labels: approved, lgtm, size/L

#225 Improvements
  Bank.ExchangeService/.env.template
  Bank.ExchangeService/Application/ExchangeApplication.cs
  Bank.ExchangeService/Configurations/ApplicationConfiguration.cs
  Bank.UserService/.env.template
  Bank.UserService/Application/UserApplication.cs
  Bank.UserService/Configurations/ApplicationConfiguration.cs
  Bank.UserService/Properties/launchSettings.json
Labels: approved, lgtm
